apiVersion: v1
kind: Service
metadata:
  namespace: myapp
  name: frontend
spec:
  type: ClusterIP
  ports:
    - port: 4200
      targetPort: 4200
      protocol: TCP
      name: http
  selector:
    app: frontend