apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
 name: mysql
commonLabels:
  app: mysql

resources:
- namespaces.yaml
- deployment.yaml
- service.yaml
- configmap.yaml
- volume.yaml
- secret.yaml