apiVersion: v1
kind: Service
metadata:
  namespace: myapp
  name: mysql
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
      name: http
  selector:
    app: mysql