apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
 name: myjava
commonLabels:
  app: myjava

resources:
- deployment.yaml
- service.yaml
- configmap.yaml
- secret.yaml
- h-autoscaler.yaml
- ingress.yaml